name: Auto Commit JS/TS File

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # setiap 5 menit

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create random JS & TS files
        run: |
          random_number=$((100000000 + RANDOM % 900000000))
          timestamp=$(date)
      
          js_filename="${random_number}.js"
          ts_filename="${random_number}.ts"
      
          echo "console.log('Generated at $timestamp');" > "$js_filename"
      
          echo "const greet = (name: string): void => {
            console.log(\`Hello, \${name}! ($timestamp)\`);
          };
          greet('TypeScript User');" > "$ts_filename"


      - name: Commit and push files
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Add random JS and TS files" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
